# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_change.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_change.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63onfig_change.proto\"\xa3\x01\n\x13\x43onfigChangeRequest\x12$\n\x0c\x65nqueue_rule\x18\x01 \x01(\x0b\x32\x0c.EnqueueRuleH\x00\x12$\n\x0crouting_rule\x18\x02 \x01(\x0b\x32\x0c.RoutingRuleH\x00\x12 \n\nqueue_info\x18\x03 \x01(\x0b\x32\n.QueueInfoH\x00\x12\x10\n\x08reporter\x18\x04 \x01(\tB\x0c\n\nConfigType\"\x80\x01\n\x0b\x45nqueueRule\x12$\n\x07\x63hanges\x18\x01 \x03(\x0b\x32\x13.EnqueueRule.Change\x1aK\n\x06\x43hange\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\r\n\x05queue\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x03(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\"u\n\x0bRoutingRule\x12$\n\x07\x63hanges\x18\x04 \x03(\x0b\x32\x13.RoutingRule.Change\x1a@\n\x06\x43hange\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\r\n\x05queue\x18\x02 \x01(\t\x12\x17\n\x0fpossible_routes\x18\x03 \x03(\t\"g\n\tQueueInfo\x12\"\n\x07\x63hanges\x18\x04 \x03(\x0b\x32\x11.QueueInfo.Change\x1a\x36\n\x06\x43hange\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\r\n\x05queue\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x03(\tb\x06proto3')
)




_CONFIGCHANGEREQUEST = _descriptor.Descriptor(
  name='ConfigChangeRequest',
  full_name='ConfigChangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enqueue_rule', full_name='ConfigChangeRequest.enqueue_rule', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='routing_rule', full_name='ConfigChangeRequest.routing_rule', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue_info', full_name='ConfigChangeRequest.queue_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reporter', full_name='ConfigChangeRequest.reporter', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ConfigType', full_name='ConfigChangeRequest.ConfigType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=24,
  serialized_end=187,
)


_ENQUEUERULE_CHANGE = _descriptor.Descriptor(
  name='Change',
  full_name='EnqueueRule.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='EnqueueRule.Change.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue', full_name='EnqueueRule.Change.queue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='EnqueueRule.Change.features', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='EnqueueRule.Change.priority', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=318,
)

_ENQUEUERULE = _descriptor.Descriptor(
  name='EnqueueRule',
  full_name='EnqueueRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='changes', full_name='EnqueueRule.changes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENQUEUERULE_CHANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=318,
)


_ROUTINGRULE_CHANGE = _descriptor.Descriptor(
  name='Change',
  full_name='RoutingRule.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='RoutingRule.Change.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue', full_name='RoutingRule.Change.queue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='possible_routes', full_name='RoutingRule.Change.possible_routes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=437,
)

_ROUTINGRULE = _descriptor.Descriptor(
  name='RoutingRule',
  full_name='RoutingRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='changes', full_name='RoutingRule.changes', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ROUTINGRULE_CHANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=437,
)


_QUEUEINFO_CHANGE = _descriptor.Descriptor(
  name='Change',
  full_name='QueueInfo.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='QueueInfo.Change.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue', full_name='QueueInfo.Change.queue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='QueueInfo.Change.owner', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=542,
)

_QUEUEINFO = _descriptor.Descriptor(
  name='QueueInfo',
  full_name='QueueInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='changes', full_name='QueueInfo.changes', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUEUEINFO_CHANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=542,
)

_CONFIGCHANGEREQUEST.fields_by_name['enqueue_rule'].message_type = _ENQUEUERULE
_CONFIGCHANGEREQUEST.fields_by_name['routing_rule'].message_type = _ROUTINGRULE
_CONFIGCHANGEREQUEST.fields_by_name['queue_info'].message_type = _QUEUEINFO
_CONFIGCHANGEREQUEST.oneofs_by_name['ConfigType'].fields.append(
  _CONFIGCHANGEREQUEST.fields_by_name['enqueue_rule'])
_CONFIGCHANGEREQUEST.fields_by_name['enqueue_rule'].containing_oneof = _CONFIGCHANGEREQUEST.oneofs_by_name['ConfigType']
_CONFIGCHANGEREQUEST.oneofs_by_name['ConfigType'].fields.append(
  _CONFIGCHANGEREQUEST.fields_by_name['routing_rule'])
_CONFIGCHANGEREQUEST.fields_by_name['routing_rule'].containing_oneof = _CONFIGCHANGEREQUEST.oneofs_by_name['ConfigType']
_CONFIGCHANGEREQUEST.oneofs_by_name['ConfigType'].fields.append(
  _CONFIGCHANGEREQUEST.fields_by_name['queue_info'])
_CONFIGCHANGEREQUEST.fields_by_name['queue_info'].containing_oneof = _CONFIGCHANGEREQUEST.oneofs_by_name['ConfigType']
_ENQUEUERULE_CHANGE.containing_type = _ENQUEUERULE
_ENQUEUERULE.fields_by_name['changes'].message_type = _ENQUEUERULE_CHANGE
_ROUTINGRULE_CHANGE.containing_type = _ROUTINGRULE
_ROUTINGRULE.fields_by_name['changes'].message_type = _ROUTINGRULE_CHANGE
_QUEUEINFO_CHANGE.containing_type = _QUEUEINFO
_QUEUEINFO.fields_by_name['changes'].message_type = _QUEUEINFO_CHANGE
DESCRIPTOR.message_types_by_name['ConfigChangeRequest'] = _CONFIGCHANGEREQUEST
DESCRIPTOR.message_types_by_name['EnqueueRule'] = _ENQUEUERULE
DESCRIPTOR.message_types_by_name['RoutingRule'] = _ROUTINGRULE
DESCRIPTOR.message_types_by_name['QueueInfo'] = _QUEUEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigChangeRequest = _reflection.GeneratedProtocolMessageType('ConfigChangeRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGCHANGEREQUEST,
  __module__ = 'config_change_pb2'
  # @@protoc_insertion_point(class_scope:ConfigChangeRequest)
  ))
_sym_db.RegisterMessage(ConfigChangeRequest)

EnqueueRule = _reflection.GeneratedProtocolMessageType('EnqueueRule', (_message.Message,), dict(

  Change = _reflection.GeneratedProtocolMessageType('Change', (_message.Message,), dict(
    DESCRIPTOR = _ENQUEUERULE_CHANGE,
    __module__ = 'config_change_pb2'
    # @@protoc_insertion_point(class_scope:EnqueueRule.Change)
    ))
  ,
  DESCRIPTOR = _ENQUEUERULE,
  __module__ = 'config_change_pb2'
  # @@protoc_insertion_point(class_scope:EnqueueRule)
  ))
_sym_db.RegisterMessage(EnqueueRule)
_sym_db.RegisterMessage(EnqueueRule.Change)

RoutingRule = _reflection.GeneratedProtocolMessageType('RoutingRule', (_message.Message,), dict(

  Change = _reflection.GeneratedProtocolMessageType('Change', (_message.Message,), dict(
    DESCRIPTOR = _ROUTINGRULE_CHANGE,
    __module__ = 'config_change_pb2'
    # @@protoc_insertion_point(class_scope:RoutingRule.Change)
    ))
  ,
  DESCRIPTOR = _ROUTINGRULE,
  __module__ = 'config_change_pb2'
  # @@protoc_insertion_point(class_scope:RoutingRule)
  ))
_sym_db.RegisterMessage(RoutingRule)
_sym_db.RegisterMessage(RoutingRule.Change)

QueueInfo = _reflection.GeneratedProtocolMessageType('QueueInfo', (_message.Message,), dict(

  Change = _reflection.GeneratedProtocolMessageType('Change', (_message.Message,), dict(
    DESCRIPTOR = _QUEUEINFO_CHANGE,
    __module__ = 'config_change_pb2'
    # @@protoc_insertion_point(class_scope:QueueInfo.Change)
    ))
  ,
  DESCRIPTOR = _QUEUEINFO,
  __module__ = 'config_change_pb2'
  # @@protoc_insertion_point(class_scope:QueueInfo)
  ))
_sym_db.RegisterMessage(QueueInfo)
_sym_db.RegisterMessage(QueueInfo.Change)


# @@protoc_insertion_point(module_scope)
